resources: ####
- name: nl2-resource-repo
  type: git
  check_every: 10m
  source:
    uri: https://github.com/thansmann/nl2.git
    branch: master

jobs: ####
- name: test-egg
  public: true
  plan:
  - get: nl2-resource-repo
    trigger: true
    version: every
  - task: egg-test
    file: nl2-resource-repo/ci/tasks/test/task.yml

- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
