resources: ####
- name: nl2-resource-repo
  type: git
  check_every: 10m
  source:
    uri: https://github.com/thansmann/nl2.git
    branch: master

jobs: ####
- name: test-egg
  public: true
  plan:
  - get: nl2-resource-repo
    trigger: true
    version: every
  - aggregate:
    - task: egg-test
      file: nl2-resource-repo/ci/tasks/test/task.yml
